packages:
  - "apps/*"
  - "!apps/vben-admin"
  - "packages/*"
  - "packages/@core/*"
  - "packages/@core/*/*"
  - "packages/effects/*"
  - "!**/test/**"
  - "!**/fixtures/**"
  - "!**/temp/**"
  - "!packages/tests/temp/**"
