name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Approve build scripts
        run: pnpm approve-builds || true
      - name: Lint
        run: pnpm lint --no-color || true
      - name: Build UI package (ui.css)
        run: pnpm --filter @packages/ui build --no-color
      - name: Build
        run: pnpm build --no-color
      - name: Test
        run: pnpm test --no-color || true
